### ISSUE TITLE
Potential crash in SocketHandler

### ISSUE THREAD

**Issue by OmerZ7** [Chameleon-Vision/chameleon-vision#24]
When a user disconnects while broadcastMessage is running the following exception will be thrown
```Exception in thread "EasyCamera - Vision Thread" java.util.ConcurrentModificationException
    at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
    at com.chameleonvision.web.SocketHandler.broadcastMessage(SocketHandler.java:217)
    at com.chameleonvision.web.SocketHandler.broadcastMessage(SocketHandler.java:231)
    at com.chameleonvision.vision.VisionProcess.updateUI(VisionProcess.java:181)
    at com.chameleonvision.vision.VisionProcess$VisionProcessRunnable.run(VisionProcess.java:259)
    at java.base/java.lang.Thread.run(Thread.java:835)
```
Todo: surround any crashable parts of the code with try catch

**Comment by Bankst** [comment]
Fixed.
